# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

language: en-US
tone_instructions: ""
early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: false
  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches: ["main", "develop"]

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  tools:
    phpstan:
      enabled: true
      level: max
    phpcs:
      enabled: true
    phpmd:
      enabled: true
    gitleaks:
      enabled: true
    yamllint:
      enabled: true
    markdownlint:
      enabled: true
    dotenvLint:
      enabled: true
    hadolint:
      enabled: true
    semgrep:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000

chat:
  auto_reply: true
