services:
  api_1:
    container_name: rinha_slim_api_1
    build:
      context: ./docker/dockerfiles/php
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - '9000:9000'
    networks:
      - rinha_slim
      - payment-processor
    volumes:
      - .:/var/www/html

  api_2:
    container_name: rinha_slim_api_2
    build:
      context: ./docker/dockerfiles/php
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - '9001:9000'
    networks:
      - rinha_slim
      - payment-processor
    volumes:
      - .:/var/www/html

  nginx:
    container_name: rinha_slim_nginx
    image: nginx:stable-alpine
    ports:
      - '9999:80'
    networks:
      - rinha_slim
      - payment-processor
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_1
      - api_2

  redis:
    container_name: rinha_slim_redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - rinha_slim
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

networks:
  rinha_slim:
    driver: bridge
  payment-processor:
    external: true